### ISSUE TITLE
Add ability to define a port number for the DB config

### ISSUE THREAD

**Issue by jiminoc** [jasonmoo/DumbledORM#1]
I usually create an ssh tunnel to my production mysql box using a different default port than MySQL default. It would be nice to be able to define a PORT in the dbconfig to override the default in the PDO connection

**Comment by jasonmoo** [comment]
Definitely.  I'm currently revamping the config setup.  Will have the option to define your own dsn which will allow you to make use of unix sockets as well.  Not sure on an eta.  Stay tuned.
